const MAX_QUANTITY=1000000;
const MAX_PRICE=1000000000;
const SYMBOL=/^[A-Z][A-Z0-9./-]{0,9}$/;
const MAX_BODY=16*1024;
const MAX_DEPTH=10;
const duplicates=new Map();
const TTL=300000;

const headers={
  'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer',
  'Permissions-Policy':'camera=(), microphone=(), geolocation=()',
  'Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'self'; frame-ancestors 'none'",
  'Cross-Origin-Resource-Policy':'same-origin'
};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store',...headers}});
const method=(allow)=>new Response(JSON.stringify({accepted:false,error:'Method not allowed'}),{status:405,headers:{'content-type':'application/json;charset=UTF-8','Allow':allow,...headers}});
function depth(value){const stack=[[value,0]];let max=0;while(stack.length){const [v,d]=stack.pop();max=Math.max(max,d);if(d>MAX_DEPTH)return d;if(v&&typeof v==='object')for(const child of Object.values(v))stack.push([child,d+1]);}return max;}
async function body(request){const len=request.headers.get('content-length');if(len!==null&&(!Number.isFinite(Number(len))||Number(len)>MAX_BODY))return {ok:false,status:413,error:'Request body too large'};const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>MAX_BODY)return {ok:false,status:413,error:'Request body too large'};let value;try{value=JSON.parse(raw)}catch{return {ok:false,status:400,error:'Request body must be valid JSON'}}if(!value||typeof value!=='object'||Array.isArray(value))return {ok:false,status:400,error:'Request body must be an object'};if(depth(value)>MAX_DEPTH)return {ok:false,status:400,error:'Request body nesting is too deep'};return {ok:true,value};}
function validate(input){if(input.quantity===null||typeof input.quantity==='boolean')return {ok:false,error:'Quantity must be a valid number'};if(input.price===null||typeof input.price==='boolean')return {ok:false,error:'Price must be a valid number'};const symbol=String(input.symbol||'').trim().toUpperCase(),quantity=Number(input.quantity),price=Number(input.price),side=String(input.side||'').trim().toUpperCase();if(!symbol)return {ok:false,error:'Symbol is required'};if(!SYMBOL.test(symbol))return {ok:false,error:'Invalid symbol'};if(!Number.isInteger(quantity)||quantity<=0||quantity>MAX_QUANTITY)return {ok:false,error:'Invalid quantity'};if(!Number.isFinite(price)||price<=0||price>MAX_PRICE)return {ok:false,error:'Invalid price'};if(side!=='BUY'&&side!=='SELL')return {ok:false,error:'Side must be BUY or SELL'};if(!Number.isFinite(quantity*price))return {ok:false,error:'Order calculation overflow'};return {ok:true,order:{symbol,quantity,price,side}};}
function duplicate(order){const now=Date.now();for(const [key,time] of duplicates){if(now-time>TTL)duplicates.delete(key);}const key=[order.symbol,order.quantity,order.price,order.side].join('|');if(duplicates.has(key))return true;duplicates.set(key,now);return false;}
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/health'){if(request.method!=='GET')return method('GET');return json({status:'ok',app:'NexaHunter',mode:'paper',liveExecution:false,timestamp:new Date().toISOString()});}if(url.pathname==='/api/paper-orders'){if(request.method!=='POST')return method('POST');if(!(request.headers.get('content-type')||'').toLowerCase().startsWith('application/json'))return json({accepted:false,error:'Content-Type must be application/json'},415);const parsed=await body(request);if(!parsed.ok)return json({accepted:false,error:parsed.error},parsed.status);const result=validate(parsed.value);if(!result.ok)return json({accepted:false,error:result.error},400);if(duplicate(result.order))return json({accepted:false,error:'Duplicate paper order rejected'},409);return json({accepted:true,message:'Paper order queued',order:{id:crypto.randomUUID(),...result.order,mode:'PAPER',liveExecution:false,timestamp:new Date().toISOString()}});}if(env?.ASSETS)return env.ASSETS.fetch(request);return new Response('NexaHunter assets unavailable',{status:503,headers:headers});}};
