import base from './worker-app.js';
import { oauthLogin, oauthCallback, logout, session, accessIdentity, accessConfig, unauthorized, safeUser } from './src/auth.js';
export { IdempotencyDurableObject, PortfolioDurableObject, MarketStreamDurableObject } from './worker-app.js';

const headers={'content-type':'application/json;charset=UTF-8','cache-control':'no-store','X-Content-Type-Options':'nosniff'};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{...headers}});
const pair=v=>String(v||'').trim().toUpperCase().includes('/')?String(v).trim().toUpperCase():`${String(v||'').trim().toUpperCase()}/USD`;
const allowed=['1Min','5Min','15Min','1Hour','1Day'];
const STOCK_SYMBOL=/^[A-Z][A-Z0-9./-]{0,9}$/;
const MAX_PAPER_QUANTITY=1000000;
const paperDuplicates=new Map();
const PAPER_DUPLICATE_TTL=300000;
const localRate=new Map();
const RATE_LIMIT=120;
const RATE_WINDOW=60000;

function auth(env){if(!env?.ALPACA_API_KEY||!env?.ALPACA_API_SECRET)return null;return {'APCA-API-KEY-ID':env.ALPACA_API_KEY,'APCA-API-SECRET-KEY':env.ALPACA_API_SECRET,'Accept':'application/json'};}
async function alpaca(env,url){const h=auth(env);if(!h)return {ok:false,status:503,error:'Market data is not configured'};try{const r=await fetch(url,{headers:h,cf:{cacheTtl:0,cacheEverything:false}});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={message:text}};return r.ok?{ok:true,data}:{ok:false,status:r.status,error:data?.message||'Market data request failed',data};}catch{return {ok:false,status:502,error:'Unable to reach market-data provider'};}}
async function cryptoBars(request,env){const u=new URL(request.url),symbol=pair(u.searchParams.get('symbol')),timeframe=allowed.includes(u.searchParams.get('timeframe'))?u.searchParams.get('timeframe'):'1Min',limit=Math.min(Math.max(Number(u.searchParams.get('limit')||500),1),1000),params=new URLSearchParams({symbols:symbol,timeframe,limit:String(limit),sort:'asc'});if(u.searchParams.get('start'))params.set('start',u.searchParams.get('start'));if(u.searchParams.get('end'))params.set('end',u.searchParams.get('end'));const r=await alpaca(env,`https://data.alpaca.markets/v1beta3/crypto/us/bars?${params}`);if(!r.ok)return json({error:r.error,provider:r.data},r.status||502);return json({symbol,timeframe,bars:r.data?.bars?.[symbol]||[],timestamp:new Date().toISOString()});}
const cgIds={bitcoin:'BTC',ethereum:'ETH',solana:'SOL',dogecoin:'DOGE',ripple:'XRP',cardano:'ADA','avalanche-2':'AVAX',litecoin:'LTC','chain-coin':'XCN'};
async function metadata(request){const u=new URL(request.url),ids=String(u.searchParams.get('ids')||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,20);if(!ids.length)return json({},200);try{const r=await fetch(`https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=${encodeURIComponent(ids.join(','))}&sparkline=false`,{cf:{cacheTtl:60,cacheEverything:false}});if(!r.ok)return json({error:'Metadata provider unavailable'},502);const rows=await r.json(),out={};for(const x of rows){out[x.id]={symbol:cgIds[x.id]||String(x.symbol||'').toUpperCase(),marketCap:x.market_cap,circulatingSupply:x.circulating_supply,high24h:x.high_24h,low24h:x.low_24h,change24h:x.price_change_percentage_24h};}return json(out);}catch{return json({error:'Metadata provider unavailable'},502);}}
function paperDuplicate(order,user){const now=Date.now();for(const [key,time] of paperDuplicates){if(now-time>PAPER_DUPLICATE_TTL)paperDuplicates.delete(key);}const key=[user?.sub||'anonymous',order.symbol,order.quantity,order.price,order.side,order.assetType].join('|');if(paperDuplicates.has(key))return true;paperDuplicates.set(key,now);return false;}
function clientKey(request,user){return `${user?.sub||request.headers.get('cf-connecting-ip')||'anonymous'}:${new URL(request.url).pathname}`;}
async function rateLimit(request,env,user){if(env?.RATE_LIMITER){const r=await env.RATE_LIMITER.limit({key:clientKey(request,user)});return r.success;}const key=clientKey(request,user),now=Date.now(),row=localRate.get(key);if(!row||now-row.start>=RATE_WINDOW){localRate.set(key,{start:now,count:1});return true;}row.count++;return row.count<=RATE_LIMIT;}
function rateResponse(){return new Response(JSON.stringify({error:'Rate limit exceeded'}),{status:429,headers:{...headers,'Retry-After':'60'}});}
async function paperPortfolio(env,userId,order){if(!env?.PORTFOLIO)return null;const id=env.PORTFOLIO.idFromName(`paper:${userId}`);const stub=env.PORTFOLIO.get(id);return stub.fetch(new Request('https://portfolio/portfolio',{method:'POST',headers:{'content-type':'application/json','x-nexahunter-user':userId},body:JSON.stringify(order)}));}
async function portfolioSnapshot(env,userId){if(!env?.PORTFOLIO)return null;const id=env.PORTFOLIO.idFromName(`paper:${userId}`);const stub=env.PORTFOLIO.get(id);return stub.fetch(new Request('https://portfolio/portfolio',{method:'GET',headers:{'x-nexahunter-user':userId}}));}
async function fractionalPaperOrder(request,env,user){if(request.method!=='POST')return json({accepted:false,error:'Method not allowed'},405);if(!(request.headers.get('content-type')||'').toLowerCase().startsWith('application/json'))return json({accepted:false,error:'Content-Type must be application/json'},415);let input;try{input=await request.json()}catch{return json({accepted:false,error:'Request body must be valid JSON'},400);}if(!input||typeof input!=='object'||Array.isArray(input))return json({accepted:false,error:'Request body must be an object'},400);const symbol=String(input.symbol||'').trim().toUpperCase();const quantity=Number(input.quantity);const price=Number(input.price);const side=String(input.side||'').trim().toUpperCase();const assetType=String(input.assetType||'STOCK').trim().toUpperCase();if(!symbol)return json({accepted:false,error:'Symbol is required'},400);if(!STOCK_SYMBOL.test(symbol))return json({accepted:false,error:'Invalid symbol'},400);if(!['STOCK','CRYPTO'].includes(assetType))return json({accepted:false,error:'Invalid asset type'},400);if(!Number.isFinite(quantity)||quantity<=0||quantity>MAX_PAPER_QUANTITY)return json({accepted:false,error:'Invalid quantity'},400);if(!Number.isFinite(price)||price<=0)return json({accepted:false,error:'Invalid price'},400);if(side!=='BUY'&&side!=='SELL')return json({accepted:false,error:'Side must be BUY or SELL'},400);if(!Number.isFinite(quantity*price))return json({accepted:false,error:'Order calculation overflow'},400);const order={id:crypto.randomUUID(),symbol,quantity,price,side,assetType,mode:'PAPER',liveExecution:false,timestamp:new Date().toISOString()};if(paperDuplicate(order,user))return json({accepted:false,error:'Duplicate paper order rejected'},409);const response=await paperPortfolio(env,user.sub,order);if(!response)return json({accepted:true,message:'Paper order queued',order,persistent:false});return new Response(await response.text(),{status:response.status,headers:{...Object.fromEntries(response.headers),...headers}});}
const PUBLIC_PATHS=new Set(['/login','/privacy','/terms','/disclaimer','/support','/favicon.ico']);
function isPublicPath(path){return PUBLIC_PATHS.has(path)||path.startsWith('/assets/');}
function isPublicMarketPath(path){return path==='/api/market/stream'||path.startsWith('/api/market/')||path==='/api/crypto/metadata';}
async function authenticatedUser(request,env,ctx){const local=await session(request,env);if(local)return local;if(ctx?.access){try{const identity=await ctx.access.getIdentity();if(identity&&(identity.id||identity.email))return {sub:String(identity.id||identity.email),email:String(identity.email||''),name:String(identity.name||identity.email||'Cloudflare Access user')};}catch{}}return accessIdentity(request,env);}
export default {async fetch(request,env,ctx){const u=new URL(request.url);if(u.pathname==='/oauth/cloudflare/login')return oauthLogin(request,env);if(u.pathname==='/oauth/cloudflare/callback')return oauthCallback(request,env);if(u.pathname==='/logout')return logout(request,env);if(u.pathname==='/health'){const access=accessConfig(env);return json({status:'ok',app:'NexaHunter',mode:'paper',liveExecution:false,persistentPortfolio:Boolean(env?.PORTFOLIO),marketDataConfigured:Boolean(auth(env)),authenticationConfigured:Boolean(env?.SESSION_SECRET&&(env?.CLOUDFLARE_OAUTH_CLIENT_ID||access.domain&&access.aud)),accessJwtConfigured:Boolean(access.domain&&access.aud),rateLimiterConfigured:Boolean(env?.RATE_LIMITER),accessAware:true,publicMarketApi:true,timestamp:new Date().toISOString()});}
const user=await authenticatedUser(request,env,ctx);
if(u.pathname==='/api/auth/me')return user?json({authenticated:true,user:safeUser(user)}):unauthorized();
const publicMarket=isPublicMarketPath(u.pathname);
if(!user&&!publicMarket&&(u.pathname==='/'||u.pathname==='/index.html'))return Response.redirect(`${u.origin}/login`,302);
if(!user&&!publicMarket&&!isPublicPath(u.pathname)&&u.pathname.startsWith('/api/'))return unauthorized();
if(!user&&!publicMarket&&!isPublicPath(u.pathname)&&!u.pathname.startsWith('/api/'))return Response.redirect(`${u.origin}/login`,302);
if(u.pathname.startsWith('/api/')&&!(await rateLimit(request,env,user)))return rateResponse();
if(u.pathname==='/api/portfolio'&&request.method==='GET'){if(!user)return unauthorized();const response=await portfolioSnapshot(env,user.sub);if(!response)return json({unavailable:true,positions:{},orders:[],mode:'PAPER',liveExecution:false,persistent:false});return new Response(await response.text(),{status:response.status,headers:{...Object.fromEntries(response.headers),...headers}});}
if(u.pathname==='/api/paper-orders')return user?fractionalPaperOrder(request,env,user):unauthorized();
if(u.pathname==='/api/market/crypto-bars'&&request.method==='GET')return cryptoBars(request,env);
if(u.pathname==='/api/crypto/metadata'&&request.method==='GET')return metadata(request);
const forwarded=new Request(request,{headers:new Headers(request.headers)});if(user)forwarded.headers.set('x-nexahunter-user',user.sub);return base.fetch(forwarded,env,ctx);}};
