const MAX_QUANTITY=1000000;
const MAX_PRICE=1000000000;
const SYMBOL=/^[A-Z][A-Z0-9./-]{0,9}$/;
const MAX_BODY=16*1024;
const MAX_DEPTH=10;
const duplicates=new Map();
const TTL=300000;
const headers={'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' wss:; img-src 'self' data:; object-src 'none'; base-uri 'self'; frame-ancestors 'none'",'Cross-Origin-Resource-Policy':'same-origin'};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store',...headers}});
const method=(allow)=>new Response(JSON.stringify({accepted:false,error:'Method not allowed'}),{status:405,headers:{'content-type':'application/json;charset=UTF-8','Allow':allow,...headers}});
function depth(value){const stack=[[value,0]];let max=0;while(stack.length){const [v,d]=stack.pop();max=Math.max(max,d);if(d>MAX_DEPTH)return d;if(v&&typeof v==='object')for(const child of Object.values(v))stack.push([child,d+1]);}return max;}
async function body(request){const len=request.headers.get('content-length');if(len!==null&&(!Number.isFinite(Number(len))||Number(len)<0||Number(len)>MAX_BODY))return {ok:false,status:413,error:'Request body too large'};const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>MAX_BODY)return {ok:false,status:413,error:'Request body too large'};let value;try{value=JSON.parse(raw)}catch{return {ok:false,status:400,error:'Request body must be valid JSON'}}if(!value||typeof value!=='object'||Array.isArray(value))return {ok:false,status:400,error:'Request body must be an object'};if(depth(value)>MAX_DEPTH)return {ok:false,status:400,error:'Request body nesting is too deep'};return {ok:true,value};}
function validate(input){if(input.quantity===null||typeof input.quantity==='boolean')return {ok:false,error:'Quantity must be a valid number'};if(input.price===null||typeof input.price==='boolean')return {ok:false,error:'Price must be a valid number'};const symbol=String(input.symbol||'').trim().toUpperCase(),quantity=Number(input.quantity),price=Number(input.price),side=String(input.side||'').trim().toUpperCase();if(!symbol)return {ok:false,error:'Symbol is required'};if(!SYMBOL.test(symbol))return {ok:false,error:'Invalid symbol'};if(!Number.isInteger(quantity)||quantity<=0||quantity>MAX_QUANTITY)return {ok:false,error:'Invalid quantity'};if(!Number.isFinite(price)||price<=0||price>MAX_PRICE)return {ok:false,error:'Invalid price'};if(side!=='BUY'&&side!=='SELL')return {ok:false,error:'Side must be BUY or SELL'};if(!Number.isFinite(quantity*price))return {ok:false,error:'Order calculation overflow'};return {ok:true,order:{symbol,quantity,price,side}};}
function duplicate(order){const now=Date.now();for(const [key,time] of duplicates){if(now-time>TTL)duplicates.delete(key);}const key=[order.symbol,order.quantity,order.price,order.side].join('|');if(duplicates.has(key))return true;duplicates.set(key,now);return false;}
async function portfolioRequest(env,path,methodName,order){if(!env?.PORTFOLIO)return null;const id=env.PORTFOLIO.idFromName('default-paper-account');const stub=env.PORTFOLIO.get(id);return stub.fetch(new Request(`https://portfolio${path}`,{method:methodName,headers:{'content-type':'application/json'},body:order?JSON.stringify(order):undefined}));}
function alpacaHeaders(env){if(!env?.ALPACA_API_KEY||!env?.ALPACA_API_SECRET)return null;return {'APCA-API-KEY-ID':env.ALPACA_API_KEY,'APCA-API-SECRET-KEY':env.ALPACA_API_SECRET,'Accept':'application/json'};}
async function alpacaFetch(env,url){const h=alpacaHeaders(env);if(!h)return {ok:false,status:503,error:'Market data is not configured. Add ALPACA_API_KEY and ALPACA_API_SECRET to the Worker secrets.'};try{const r=await fetch(url,{headers:h,cf:{cacheTtl:0,cacheEverything:false}});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={message:text}}if(!r.ok)return {ok:false,status:r.status,error:data?.message||'Alpaca request failed',data};return {ok:true,status:r.status,data};}catch(error){return {ok:false,status:502,error:'Unable to reach market-data provider'};}}
function stockSymbols(value){return String(value||'').split(',').map(s=>s.trim().toUpperCase()).filter(Boolean).filter(s=>SYMBOL.test(s)).slice(0,30);}
function cryptoSymbols(value){return String(value||'').split(',').map(s=>s.trim().toUpperCase()).filter(Boolean).map(s=>s.includes('/')?s:`${s}/USD`).slice(0,10);}
async function marketSnapshot(request,env){const url=new URL(request.url);const symbols=stockSymbols(url.searchParams.get('symbols'));const crypto=cryptoSymbols(url.searchParams.get('crypto'));if(!symbols.length&&!crypto.length)return json({error:'Provide symbols or crypto query parameters'},400);const result={stocks:{},crypto:{},timestamp:new Date().toISOString(),feed:'iex'};if(symbols.length){const r=await alpacaFetch(env,`https://data.alpaca.markets/v2/stocks/snapshots?symbols=${encodeURIComponent(symbols.join(','))}&feed=iex`);if(!r.ok)return json({error:r.error,provider:r.data},r.status);result.stocks=r.data||{};}if(crypto.length){const r=await alpacaFetch(env,`https://data.alpaca.markets/v1beta3/crypto/us/snapshots?symbols=${encodeURIComponent(crypto.join(','))}`);if(!r.ok)return json({error:r.error,provider:r.data},r.status);result.crypto=r.data||{};}return json(result);}
async function marketBars(request,env){const url=new URL(request.url);const symbol=String(url.searchParams.get('symbol')||'').trim().toUpperCase();if(!SYMBOL.test(symbol))return json({error:'Invalid symbol'},400);const timeframe=['1Min','5Min','15Min','1Hour','1Day'].includes(url.searchParams.get('timeframe'))?url.searchParams.get('timeframe'):'1Min';const limit=Math.min(Math.max(Number(url.searchParams.get('limit')||100),1),1000);const feed='iex';const r=await alpacaFetch(env,`https://data.alpaca.markets/v2/stocks/${encodeURIComponent(symbol)}/bars?timeframe=${encodeURIComponent(timeframe)}&limit=${limit}&feed=${feed}&sort=asc`);if(!r.ok)return json({error:r.error,provider:r.data},r.status);return json({symbol,timeframe,bars:r.data?.bars||[],timestamp:new Date().toISOString()});}
async function marketClock(env){const r=await alpacaFetch(env,'https://paper-api.alpaca.markets/v2/clock');if(!r.ok)return json({error:r.error,provider:r.data},r.status);return json(r.data);}
async function streamConfig(env){if(!alpacaHeaders(env))return json({enabled:false,error:'Market data is not configured'},503);return json({enabled:true,stock:{url:'wss://stream.data.alpaca.markets/v2/iex'},crypto:{url:'wss://stream.data.alpaca.markets/v1beta3/crypto/us'}});}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null;}function pct(a,b){return a&&b?((a/b)-1)*100:null;}
function signalFrom(s){const q=s?.dailyBar?.c??s?.latestTrade?.p??s?.prevDailyBar?.c;const prev=s?.prevDailyBar?.c;const day=pct(num(q),num(prev));const av=s?.dailyBar?.v;const pv=s?.prevDailyBar?.v;const vol=av&&pv?av/pv:null;const score=Math.max(0,Math.min(100,50+(day||0)*7+(vol?Math.min(20,(vol-1)*20):0)));let label=score>=72?'STRONG BUY':score>=58?'BUY':score<=35?'SELL':'HOLD';return {label,confidence:Math.round(score),price:num(q),changePercent:day,volumeRatio:vol};}
async function intelligence(request,env){const url=new URL(request.url);const symbols=stockSymbols(url.searchParams.get('symbols')||'AAPL,NVDA,TSLA,AMZN,AMD,PLTR,CRWD');const r=await alpacaFetch(env,`https://data.alpaca.markets/v2/stocks/snapshots?symbols=${encodeURIComponent(symbols.join(','))}&feed=iex`);if(!r.ok)return json({error:r.error,provider:r.data},r.status);const rows=Object.entries(r.data||{}).map(([symbol,snapshot])=>({symbol,signal:signalFrom(snapshot)})).filter(x=>x.signal.price!==null);const movers=[...rows].sort((a,b)=>(b.signal.changePercent??-Infinity)-(a.signal.changePercent??-Infinity));const strongest=[...rows].sort((a,b)=>b.signal.confidence-a.signal.confidence)[0]||null;const alerts=rows.filter(x=>Math.abs(x.signal.changePercent||0)>=2||x.signal.confidence>=72).slice(0,6).map(x=>({symbol:x.symbol,type:x.signal.changePercent>=2?'Momentum':'AI Signal',message:x.signal.changePercent>=2?'Breakout / momentum detected':x.signal.label,changePercent:x.signal.changePercent,confidence:x.signal.confidence}));return json({timestamp:new Date().toISOString(),feed:'iex',signals:rows,movers,alerts,strongest});}
async function conceptStyles(request,env){if(!env?.ASSETS)return null;const base=await env.ASSETS.fetch(request);if(!base.ok)return base;const fixUrl=new URL('/fix.css?v=concept-20260824',request.url);const fix=await env.ASSETS.fetch(new Request(fixUrl.toString(),{method:'GET',headers:{'Accept':'text/css'}}));if(!fix.ok)return base;const css=(await base.text())+'\n/* NexaHunter concept lock */\n'+await fix.text();return new Response(css,{status:200,headers:{...headers,'content-type':'text/css; charset=UTF-8','cache-control':'no-store'}});}
async function conceptHtml(request,env){if(!env?.ASSETS)return null;const base=await env.ASSETS.fetch(request);if(!base.ok)return base;let html=await base.text();if(!html.includes('/panels.js'))html=html.replace('</body>','<script src="/panels.js?v=master-functional-20260824" defer></script></body>');if(!html.includes('/intelligence.js'))html=html.replace('</body>','<script src="/intelligence.js?v=live-intelligence-20260824" defer></script></body>');return new Response(html,{status:base.status,headers:{...headers,'content-type':'text/html; charset=UTF-8','cache-control':'no-store'}});}
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/health'){if(request.method!=='GET')return method('GET');return json({status:'ok',app:'NexaHunter',mode:'paper',liveExecution:false,persistentPortfolio:Boolean(env?.PORTFOLIO),marketDataConfigured:Boolean(alpacaHeaders(env)),timestamp:new Date().toISOString()});}if(url.pathname==='/api/market/snapshot'){if(request.method!=='GET')return method('GET');return marketSnapshot(request,env);}if(url.pathname==='/api/market/bars'){if(request.method!=='GET')return method('GET');return marketBars(request,env);}if(url.pathname==='/api/market/clock'){if(request.method!=='GET')return method('GET');return marketClock(env);}if(url.pathname==='/api/market/stream-config'){if(request.method!=='GET')return method('GET');return streamConfig(env);}if(url.pathname==='/api/intelligence'){if(request.method!=='GET')return method('GET');return intelligence(request,env);}if(url.pathname==='/api/portfolio'){if(request.method!=='GET')return method('GET');const response=await portfolioRequest(env,'/portfolio','GET');if(!response)return json({cash:100000,positions:{},orders:[],mode:'PAPER',liveExecution:false,persistent:false});return new Response(await response.text(),{status:response.status,headers:{...Object.fromEntries(response.headers),...headers}});}if(url.pathname==='/api/paper-orders'){if(request.method!=='POST')return method('POST');if(!(request.headers.get('content-type')||'').toLowerCase().startsWith('application/json'))return json({accepted:false,error:'Content-Type must be application/json'},415);const parsed=await body(request);if(!parsed.ok)return json({accepted:false,error:parsed.error},parsed.status);const result=validate(parsed.value);if(!result.ok)return json({accepted:false,error:result.error},400);if(duplicate(result.order))return json({accepted:false,error:'Duplicate paper order rejected'},409);const order={id:crypto.randomUUID(),...result.order,mode:'PAPER',liveExecution:false,timestamp:new Date().toISOString()};const response=await portfolioRequest(env,'/portfolio','POST',order);if(!response)return json({accepted:true,message:'Paper order queued',order,persistent:false});const text=await response.text();return new Response(text,{status:response.status,headers:{...Object.fromEntries(response.headers),...headers}});}if(url.pathname==='/styles.css'&&request.method==='GET')return conceptStyles(request,env);if((url.pathname==='/'||url.pathname==='/index.html')&&request.method==='GET')return conceptHtml(request,env);if(env?.ASSETS)return env.ASSETS.fetch(request);return new Response('NexaHunter assets unavailable',{status:503,headers});}};
export { IdempotencyDurableObject } from './src/idempotency.js';
export { PortfolioDurableObject } from './src/portfolio.js';
