import base from './worker-app.js';
export { IdempotencyDurableObject, PortfolioDurableObject, MarketStreamDurableObject } from './worker-app.js';

const headers={'content-type':'application/json;charset=UTF-8','cache-control':'no-store','X-Content-Type-Options':'nosniff'};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers});
const pair=v=>String(v||'').trim().toUpperCase().includes('/')?String(v).trim().toUpperCase():`${String(v||'').trim().toUpperCase()}/USD`;
const allowed=['1Min','5Min','15Min','1Hour','1Day'];
function auth(env){if(!env?.ALPACA_API_KEY||!env?.ALPACA_API_SECRET)return null;return {'APCA-API-KEY-ID':env.ALPACA_API_KEY,'APCA-API-SECRET-KEY':env.ALPACA_API_SECRET,'Accept':'application/json'};}
async function alpaca(env,url){const h=auth(env);if(!h)return {ok:false,status:503,error:'Market data is not configured'};try{const r=await fetch(url,{headers:h,cf:{cacheTtl:0,cacheEverything:false}});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={message:text}};return r.ok?{ok:true,data}:{ok:false,status:r.status,error:data?.message||'Market data request failed',data};}catch{return {ok:false,status:502,error:'Unable to reach market-data provider'};}}
async function cryptoBars(request,env){const u=new URL(request.url),symbol=pair(u.searchParams.get('symbol')),timeframe=allowed.includes(u.searchParams.get('timeframe'))?u.searchParams.get('timeframe'):'1Min',limit=Math.min(Math.max(Number(u.searchParams.get('limit')||500),1),1000),params=new URLSearchParams({symbols:symbol,timeframe,limit:String(limit),sort:'asc'});if(u.searchParams.get('start'))params.set('start',u.searchParams.get('start'));if(u.searchParams.get('end'))params.set('end',u.searchParams.get('end'));const r=await alpaca(env,`https://data.alpaca.markets/v1beta3/crypto/us/bars?${params}`);if(!r.ok)return json({error:r.error,provider:r.data},r.status||502);return json({symbol,timeframe,bars:r.data?.bars?.[symbol]||[],timestamp:new Date().toISOString()});}
const cgIds={bitcoin:'BTC',ethereum:'ETH',solana:'SOL',dogecoin:'DOGE',ripple:'XRP',cardano:'ADA','avalanche-2':'AVAX',litecoin:'LTC','chain-coin':'XCN'};
async function metadata(request){const u=new URL(request.url),ids=String(u.searchParams.get('ids')||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,20);if(!ids.length)return json({},200);try{const r=await fetch(`https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=${encodeURIComponent(ids.join(','))}&sparkline=false`,{cf:{cacheTtl:60,cacheEverything:false}});if(!r.ok)return json({error:'Metadata provider unavailable'},502);const rows=await r.json(),out={};for(const x of rows){out[x.id]={symbol:cgIds[x.id]||String(x.symbol||'').toUpperCase(),marketCap:x.market_cap,circulatingSupply:x.circulating_supply,high24h:x.high_24h,low24h:x.low_24h,change24h:x.price_change_percentage_24h};}return json(out);}catch{return json({error:'Metadata provider unavailable'},502);}}
export default {async fetch(request,env,ctx){const u=new URL(request.url);if(u.pathname==='/api/market/crypto-bars'&&request.method==='GET')return cryptoBars(request,env);if(u.pathname==='/api/crypto/metadata'&&request.method==='GET')return metadata(request);return base.fetch(request,env,ctx);}};
