name = "nexahunter"
main = "worker-app.js"
compatibility_date = "2026-08-24"

[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "IDEMPOTENCY"
class_name = "IdempotencyDurableObject"

[[durable_objects.bindings]]
name = "PORTFOLIO"
class_name = "PortfolioDurableObject"

[[durable_objects.bindings]]
name = "MARKET_STREAM"
class_name = "MarketStreamDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["IdempotencyDurableObject"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["PortfolioDurableObject"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["MarketStreamDurableObject"]
