name = "nexahunter"
main = "worker-app.js"
compatibility_date = "2026-08-23"

[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "IDEMPOTENCY"
class_name = "IdempotencyDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["IdempotencyDurableObject"]
