const AUTH_COOKIE='nexa_session';
const STATE_COOKIE='nexa_oauth_state';
const VERIFIER_COOKIE='nexa_oauth_verifier';
const CF_AUTH='https://dash.cloudflare.com/oauth2/auth';
const CF_TOKEN='https://dash.cloudflare.com/oauth2/token';
const CF_USERINFO='https://dash.cloudflare.com/oauth2/userinfo';
let accessJwksCache={expiresAt:0,keys:new Map(),domain:''};
function b64url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function b64urlBytes(value){const normalized=String(value||'').replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(String(value||'').length/4)*4,'=');return Uint8Array.from(atob(normalized),c=>c.charCodeAt(0));}
function utf8b64url(text){return b64url(new TextEncoder().encode(text));}
async function sha256(text){return new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)));}
async function randomToken(){return b64url(crypto.getRandomValues(new Uint8Array(32)));}
async function pkce(){const verifier=await randomToken();const challenge=b64url(await sha256(verifier));return {verifier,challenge};}
async function sign(payload,secret){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const body=utf8b64url(JSON.stringify(payload));const sig=b64url(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(body))));return `${body}.${sig}`;}
async function verify(token,secret){try{const [body,sig]=String(token||'').split('.');if(!body||!sig||!secret)return null;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);const ok=await crypto.subtle.verify('HMAC',key,b64urlBytes(sig),new TextEncoder().encode(body));if(!ok)return null;const payload=JSON.parse(new TextDecoder().decode(b64urlBytes(body)));return payload.exp>Date.now()/1000?payload:null;}catch{return null;}}
function normalizeAccessDomain(value){const domain=String(value||'').trim().replace(/\/$/,'');return /^https:\/\/[^/]+\.cloudflareaccess\.com$/.test(domain)?domain:null;}
async function accessKeys(domain){const now=Date.now();if(accessJwksCache.domain===domain&&accessJwksCache.expiresAt>now&&accessJwksCache.keys.size)return accessJwksCache.keys;const response=await fetch(`${domain}/cdn-cgi/access/certs`,{cf:{cacheTtl:300,cacheEverything:false}});if(!response.ok)throw new Error('Access signing keys unavailable');const body=await response.json();const keys=new Map();for(const key of Array.isArray(body?.keys)?body.keys:[]){if(key?.kid&&key?.kty==='RSA'&&key?.alg==='RS256')keys.set(String(key.kid),key);}if(!keys.size)throw new Error('Access signing keys missing');accessJwksCache={domain,expiresAt:now+300000,keys};return keys;}
async function verifyAccessToken(token,env){try{const parts=String(token||'').split('.');if(parts.length!==3)return null;const header=JSON.parse(new TextDecoder().decode(b64urlBytes(parts[0])));const payload=JSON.parse(new TextDecoder().decode(b64urlBytes(parts[1])));if(header?.alg!=='RS256'||!header?.kid||payload?.type!=='app')return null;const domain=normalizeAccessDomain(env?.CLOUDFLARE_ACCESS_TEAM_DOMAIN);const aud=String(env?.CLOUDFLARE_ACCESS_AUD||'').trim();if(!domain||!aud)return null;if(payload.iss!==domain)return null;const audiences=Array.isArray(payload.aud)?payload.aud:[payload.aud];if(!audiences.includes(aud))return null;const now=Math.floor(Date.now()/1000);if(!Number.isFinite(Number(payload.exp))||Number(payload.exp)<=now)return null;if(payload.nbf!==undefined&&Number(payload.nbf)>now)return null;if(!payload.sub)return null;const jwk=(await accessKeys(domain)).get(String(header.kid));if(!jwk)return null;const key=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const valid=await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,b64urlBytes(parts[2]),new TextEncoder().encode(`${parts[0]}.${parts[1]}`));if(!valid)return null;return {sub:String(payload.sub),email:String(payload.email||''),name:String(payload.name||payload.email||'Cloudflare Access user')};}catch{return null;}}
export async function accessIdentity(request,env){const token=request.headers.get('Cf-Access-Jwt-Assertion');if(!token)return null;return verifyAccessToken(token,env);}
function cookies(request){const out={};for(const part of (request.headers.get('Cookie')||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim());}return out;}
function cookie(name,value,maxAge){return `${name}=${encodeURIComponent(value)}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=Lax`+(maxAge<=0?'; Expires=Thu, 01 Jan 1970 00:00:00 GMT':'');}
function redirect(url,headers={}){const h=new Headers();h.set('Location',url);for(const [key,value] of Object.entries(headers)){if(key.toLowerCase()==='set-cookie'&&Array.isArray(value)){for(const item of value)h.append('Set-Cookie',item);}else h.set(key,String(value));}return new Response(null,{status:302,headers:h});}
function origin(request,env){return env.PUBLIC_ORIGIN||new URL(request.url).origin;}
function requireConfig(env){return env.CLOUDFLARE_OAUTH_CLIENT_ID&&env.SESSION_SECRET;}
export async function session(request,env){if(!env?.SESSION_SECRET)return null;return verify(cookies(request)[AUTH_COOKIE],env.SESSION_SECRET);}
export async function oauthLogin(request,env){if(!requireConfig(env))return new Response('Authentication is not configured',{status:503});const base=origin(request,env);const state=await randomToken();const {verifier,challenge}=await pkce();const redirectUri=`${base}/oauth/cloudflare/callback`;const p=new URLSearchParams({client_id:env.CLOUDFLARE_OAUTH_CLIENT_ID,response_type:'code',redirect_uri:redirectUri,scope:env.CLOUDFLARE_OAUTH_SCOPES||'openid profile email',state,code_challenge:challenge,code_challenge_method:'S256'});return redirect(`${CF_AUTH}?${p}`,{'Set-Cookie':[cookie(STATE_COOKIE,state,600),cookie(VERIFIER_COOKIE,verifier,600)]});}
export async function oauthCallback(request,env){if(!requireConfig(env))return new Response('Authentication is not configured',{status:503});const u=new URL(request.url),c=cookies(request),code=u.searchParams.get('code'),state=u.searchParams.get('state');if(!code||!state||!c[STATE_COOKIE]||state!==c[STATE_COOKIE]||!c[VERIFIER_COOKIE])return new Response('Invalid OAuth state',{status:400});const redirectUri=`${origin(request,env)}/oauth/cloudflare/callback`;const tokenRes=await fetch(CF_TOKEN,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:env.CLOUDFLARE_OAUTH_CLIENT_ID,redirect_uri:redirectUri,code,code_verifier:c[VERIFIER_COOKIE]}),cf:{cacheTtl:0}});if(!tokenRes.ok)return new Response('OAuth token exchange failed',{status:502});const token=await tokenRes.json();if(!token.access_token)return new Response('OAuth token missing',{status:502});const userRes=await fetch(CF_USERINFO,{headers:{Authorization:`Bearer ${token.access_token}`,Accept:'application/json'},cf:{cacheTtl:0}});if(!userRes.ok)return new Response('OAuth userinfo failed',{status:502});const user=await userRes.json();if(!user.sub)return new Response('OAuth identity missing',{status:502});const now=Math.floor(Date.now()/1000);const payload={sub:String(user.sub),email:String(user.email||''),name:String(user.name||user.email||'Cloudflare user'),iat:now,exp:now+60*60*8};const signed=await sign(payload,env.SESSION_SECRET);return redirect(`${origin(request,env)}/`,{'Set-Cookie':[cookie(AUTH_COOKIE,signed,60*60*8),cookie(STATE_COOKIE,'',0),cookie(VERIFIER_COOKIE,'',0)]});}
export function logout(request,env){return redirect(`${origin(request,env)}/login`,{'Set-Cookie':cookie(AUTH_COOKIE,'',0)});
}
export function unauthorized(){return new Response(JSON.stringify({error:'Authentication required',login:'/oauth/cloudflare/login'}),{status:401,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store'}});}
export function safeUser(s){return s?{id:s.sub,email:s.email,name:s.name}:null;}
